### ISSUE TITLE
Support validating againist different MDS versions. 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/mds-validator#1]

**Comment by hunterowens** [comment]
supported in [mds-provider](https://github.com/cityofsantamonica/mds-provider)

**Comment by yoimnik** [comment]
@hunterowens hey, i don't think mds-provider nor mds-validator supports validating against different MDS versions

it seems that the current schema https://raw.githubusercontent.com/CityOfLosAngeles/mobility-data-specification/master/provider/status_changes.json is currently supporting 0.3.x and has left 0.2.x in the dust :P 

when i pull 0.2.x status changes and validate it, i get warnings saying that they're not following spec -- but it's correctly following the 0.2.x spec.

namely, the `timestamp` floating point -> integer millisecond change and field name `associated_trips` -> `associated_trip` change is what's inconsistent
